/*
******************************************************************************
* File Name          : state_estimate.h
* Description        : state(attitude, altitude, pos) estimate interface
******************************************************************************
*/

#ifndef __cplusplus
#error "Please define __cplusplus, because this is a c++ based file "
#endif

#ifndef __STATE_ESTIMATE_H
#define __STATE_ESTIMATE_H

#ifndef SIMULATION
#include "config.h"

// micro-ROS (rcl/rclc)
#include <rcl/rcl.h>
#include <rclc/rclc.h>

// Your custom message headers (generated by rosidl for micro-ROS)
#include <spinal_msgs/srv/mag_declination.h>

/* sensors */
#include "sensors/imu/drivers/mpu9250/imu_mpu9250.h"
#include "sensors/imu/drivers/icm20948/icm_20948.h"
#include "sensors/baro/baro_ms5611.h"
#include "sensors/gps/gps_ublox.h"
#endif

#include "state_estimate/attitude/attitude_estimate.h"

class StateEstimate {
 public:
  StateEstimate() {}
  ~StateEstimate() {}

#ifdef SIMULATION
  void init(std::shared_ptr<rclcpp_lifecycle::LifecycleNode> node) {
    attitude_estimate_flag_ = true;
    attitude_estimator_.init(node);
  }
#else
  void init(IMU* imu, Baro* baro, GPS* gps, rcl_node_t* node, rclc_executor_t* executor)
  {
    node_ = node;
    executor_ = executor;

    imu_ = imu;
    baro_ = baro;
    gps_ = gps;

    if (imu_ == NULL)
    {
      attitude_estimate_flag_ = false;
    }
    else
    {
      attitude_estimate_flag_ = true;
      attitude_estimator_.init(imu_, gps_, node_, executor_);
    }

    if (baro_ == NULL)
    {
      altitude_estimate_flag_ = false;
    }
    else
    {
      altitude_estimate_flag_ = true;
      // altitude_estimator_.init(imu_, baro_, node_, executor_);
    }

    if (gps_ == NULL)
    {
      pos_estimate_flag_ = false;
    }
    else
    {
      pos_estimate_flag_ = true;
      // pos_estimator_.init(imu_, gps_, node_, executor_);
    }
  }
#endif

  void update() {
    if (attitude_estimate_flag_) attitude_estimator_.update();
#ifndef SIMULATION
    // if (altitude_estimate_flag_) altitude_estimator_.update();
    // if (pos_estimate_flag_) pos_estimator_.update();
#endif
 }

  AttitudeEstimate* getAttEstimator() { return &attitude_estimator_; }

#ifndef SIMULATION
  IMU* getImu() { return imu_; }
  Baro* getBaro() { return baro_; }
  GPS* getGPS() { return gps_; }
#endif

 private:
#ifndef SIMULATION
  rcl_node_t* node_ = nullptr;
  rclc_executor_t* executor_ = nullptr;

  IMU* imu_ = nullptr;
  Baro* baro_ = nullptr;
  GPS* gps_ = nullptr;
#endif

  AttitudeEstimate attitude_estimator_;
#ifndef SIMULATION
  // AltitudeEstimate altitude_estimator_;
  // PosEstimate pos_estimator_;
#endif

  bool attitude_estimate_flag_ = false;
  bool altitude_estimate_flag_ = false;
  bool pos_estimate_flag_ = false;
};

#endif
